# Generated by Django 4.2 on 2025-03-26 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefeFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu_Fixa', models.CharField(blank=True, max_length=50, null=True)),
                ('xefe_Familia', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='XefeFamilia/')),
                ('administrativepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost', verbose_name='Postu Administrativu')),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality', verbose_name='Munisipiu')),
            ],
        ),
        migrations.CreateModel(
            name='HabilitasaunLiteraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profissaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetCidadaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=100, null=True)),
                ('seksu', models.CharField(blank=True, choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=10, null=True)),
                ('Fatin_Moris', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatin Moris')),
                ('Data_Moris', models.DateField(blank=True, null=True, verbose_name='Data , Fulan no Tinan Moris')),
                ('EStadi_Civil', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estadu Civil')),
                ('relasaun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ralasaun Familia')),
                ('Profisaun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FixaApp.profissaun')),
                ('administrativepost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost', verbose_name='Postu Administrativu')),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia')),
                ('chafeFAmila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FixaApp.chefefamilia')),
                ('habilitasaun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FixaApp.habilitasaunliteraria', verbose_name='Habilitasaun Literaria')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality', verbose_name='Munisipiu')),
                ('religiaun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FixaApp.relegiao')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village', verbose_name='Suku')),
            ],
        ),
        migrations.AddField(
            model_name='chefefamilia',
            name='tinan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FixaApp.tinan'),
        ),
        migrations.AddField(
            model_name='chefefamilia',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village', verbose_name='Suku'),
        ),
    ]
