# Generated by Django 4.2.6 on 2024-06-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsionariu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funsionariu',
            name='tipu_f',
            field=models.CharField(blank=True, choices=[('Chefe Suco', 'Chefe Suco'), ('Chefe Aldeia', 'Chefe Aldeia')], max_length=30, null=True),
        ),
    ]
